---
title: "Initial Exploration"
author: "Sunni Raleigh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Import Packages
```{r}
library(tidyverse)
library(leaflet)
```

### Load Initial Data

Uncomment the data if you lose `station-data.csv`
```{r}
bostonWeatherStationsInit <- read.csv(here::here("boston_climate_data.csv"))

bostonWeatherStations <- bostonWeatherStationsInit %>%
  select(c(
    STATION,
    NAME,
    LATITUDE,
    LONGITUDE,
    ELEVATION,
    DATE,
    PRCP,
    SNOW,
    TMAX,
    TMIN
  ))
# 
# write.csv(bostonWeatherStations, "station-data.csv", row.names = FALSE)
# 
# bostonWeatherStations <- read.csv(here::here("station-data.csv"))
```

#### Data Summary
```{r}
station_dist <- bostonWeatherStations %>%
  count(NAME) %>%
  filter(n >= quantile(n, probs = .75))
  
  # mutate(avg = ifelse(n>=median(n), 1, 0)) %>%
  # filter(avg == 1) %>%
  # select(-c(avg))

station_dist_viz <- ggplot(station_dist, aes(x=reorder(NAME, -n), y=n)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, size = 5))

station_dist_viz
summary(bostonWeatherStations$NAME)
```


#### Filter data for unique weather stations
```{r}
weather_stations_df <- bostonWeatherStations %>%
  select(c(NAME, LONGITUDE, LATITUDE)) %>%
  group_by(NAME) %>%
  unique.data.frame()
  
```


### Map
```{r}
weather_stations_map <- weather_stations_df %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~LONGITUDE, lat = ~LATITUDE, popup = ~NAME)

weather_stations_map
```

#### Exploring measures for CHESTNUT HILL, MA US
```{r}
not_all_na <- function(x) any(!is.na(x) || rlang::is_empty(x))

chestnut <- bostonWeatherStations %>%
  filter(NAME == "CHESTNUT HILL, MA US") %>%
  select(c(
    STATION,
    NAME,
    LATITUDE,
    LONGITUDE,
    ELEVATION,
    DATE,
    PRCP,
    TMAX,
    TMIN
  ))

summary(chestnut)
```

